
# Simple Linear regression
 Simple linear regression is a regression model that estimates the relationship
 between one independent variable and a dependent variable using a straight line.


 ## **Problem Statement**


 The Waist Circumference – Adipose Tissue Relationship:
 
 Studies have shown that individuals with excess Adipose tissue (AT) in 
their abdominal region have a higher risk of cardio-vascular diseases.
To assess the health conditions of a patient, doctor must get a report 
on the patients AT values. Computed Tomography, commonly called the CT Scan
is the only technique that allows for the precise and reliable measurement 
of the AT (at any site in the body). 

 
**The problems with using the CT scan are:**
 - Many physicians do not have access to this technology
 - Irradiation of the patient (suppresses the immune system)
 - Expensive
 
 The Hospital/Organization wants to find an alternative solution for this 
problem, which can allow doctors to help their patients efficiently.
 


 CRISP-ML(Q) process model describes six phases:
 
 - Business and Data Understanding
 - Data Preparation (Data Engineering)
 - Model Building (Machine Learning)
 - Model Evaluation and Tunning
 - Deployment
 - Monitoring and Maintenance
 


 **Objective(s):** Minimize the risk for patients
 or 
 Maximize the convience to doctors in assisting their patients
 
 **Constraints:** CT Scan is the only option
 
 **Research:** A group of researchers conducted a study with the aim of 
predicting abdominal AT area using simple anthropometric measurements, i.e., 
measurements on the human body

 
 **Proposed Plan:**
 The Waist Circumference – Adipose Tissue data is a part of this study wherein
 the aim is to study how well waist circumference (WC) predicts the AT area
 
 
 **Benefits:**
 Is there a simpler yet reasonably accurate way to predict the AT area? i.e.,
 - Easily available
 - Risk free
 - Inexpensive
 

 **Data Collection**
 Data: 
     AT values from the historical Data
     Waist Circumference of these patients.
 
 Collection:
 1. Evaluate the available Hospital records for relevant data (CT scan of patients)
 
 2. Record the Waist Circumference of patients - Primary Data
 
 - Strategy to Collection Primary Data:
     Call out the most recent patients (1 year old) with an offer of free 
     consultation from a senior doctor to attract them to visit hospital.
     Once the paitents visit the hospital, we can record their Waist 
     Circumference with accuracy.

## importing all lib

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk

## Getting the data

In [4]:
patient_data = pd.read_csv('ATpatients.csv')
patient_data.head()

,Patient,Sex,Age,Weight,Height,BodyFat,AT,Density,Neck,Chest,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
0,1,F,23,154.25,67.75,12.3,25.72,1.0708,36.2,93.1,94.5,59.0,37.3,21.9,32.0,27.4,17.1
1,2,M,22,173.25,72.25,6.1,25.89,1.0853,38.5,93.6,98.7,58.7,37.3,23.4,30.5,28.9,18.2
2,3,M,22,154.00,66.25,25.3,42.60,1.0414,34.0,95.8,99.2,59.6,38.9,24.0,28.8,25.2,16.6
3,4,F,26,184.75,72.25,10.4,42.80,1.0751,37.4,101.8,101.2,60.1,37.3,22.8,32.4,29.4,18.2
4,5,F,24,184.25,71.25,28.7,29.84,1.0340,34.4,97.3,101.9,63.2,42.2,24.0,32.2,27.7,17.7

In [6]:
waist = pd.read_csv('waist.csv')
waist.head()

   Patient  Waist
0        1  74.75
1        2  72.60
2        3  81.80
3        4  83.95
4        5  74.65

In [10]:
df = pd.merge(patient_data, waist, on='Patient')

In [11]:
df.head()

,Patient,Sex,Age,Weight,Height,BodyFat,AT,Density,Neck,Chest,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist,Waist
0,1,F,23,154.25,67.75,12.3,25.72,1.0708,36.2,93.1,94.5,59.0,37.3,21.9,32.0,27.4,17.1,74.75
1,2,M,22,173.25,72.25,6.1,25.89,1.0853,38.5,93.6,98.7,58.7,37.3,23.4,30.5,28.9,18.2,72.60
2,3,M,22,154.00,66.25,25.3,42.60,1.0414,34.0,95.8,99.2,59.6,38.9,24.0,28.8,25.2,16.6,81.80
3,4,F,26,184.75,72.25,10.4,42.80,1.0751,37.4,101.8,101.2,60.1,37.3,22.8,32.4,29.4,18.2,83.95
4,5,F,24,184.25,71.25,28.7,29.84,1.0340,34.4,97.3,101.9,63.2,42.2,24.0,32.2,27.7,17.7,74.65

In [12]:
df = df[['Waist','AT']]

In [13]:
df.head()

   Waist     AT
0  74.75  25.72
1  72.60  25.89
2  81.80  42.60
3  83.95  42.80
4  74.65  29.84

In [14]:
df.columns = [i.lower() for i in df.columns]

In [15]:
df.head()

   waist     at
0  74.75  25.72
1  72.60  25.89
2  81.80  42.60
3  83.95  42.80
4  74.65  29.84