In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn as sk

In [16]:
import yfinance as yf

df = yf.download("^NSEI", start="2015-01-01", end="2025-12-31",group_by="columns")

[*********************100%***********************]  1 of 1 completed

In [19]:
df.head()

Ticker            ^NSEI
Price              Open         High          Low        Close  Volume
Date
2015-01-02  8288.700195  8410.599609  8288.700195  8395.450195  101900
2015-01-05  8407.950195  8445.599609  8363.900391  8378.400391  118200
2015-01-06  8325.299805  8327.849609  8111.350098  8127.350098  172800
2015-01-07  8118.649902  8151.200195  8065.450195  8102.100098  164100
2015-01-08  8191.399902  8243.500000  8167.299805  8234.599609  143800

In [23]:
df = df['^NSEI']

In [27]:
df.columns = [i.lower() for i in df.columns]

In [28]:
df.head()

                   open         high          low        close  volume
Date
2015-01-02  8288.700195  8410.599609  8288.700195  8395.450195  101900
2015-01-05  8407.950195  8445.599609  8363.900391  8378.400391  118200
2015-01-06  8325.299805  8327.849609  8111.350098  8127.350098  172800
2015-01-07  8118.649902  8151.200195  8065.450195  8102.100098  164100
2015-01-08  8191.399902  8243.500000  8167.299805  8234.599609  143800